# Generated by Django 4.2.4 on 2023-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_message_body_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
