# Generated by Django 4.2.4 on 2023-08-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='host',
        ),
    ]
