# Generated by Django 4.2.4 on 2023-08-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_registrationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationToken',
        ),
    ]
