# Generated by Django 4.2.4 on 2023-11-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_room_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated']},
        ),
    ]
