# Generated by Django 4.2.7 on 2023-11-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_email',
            field=models.BooleanField(default=False),
        ),
    ]
